// The screen's fixed text in English and Japanese (docs/spec/screen.md, "言語"). The Japanese
// uses the glossary's words (CONTEXT.md). Text the LLM wrote never passes through here.

const en = {
  "tab.current": "Current round",
  "tab.past": "Past rounds",
  "tab.map": "Map",
  "tab.decisions": "Decisions",

  "header.untitled": "Untitled topic",
  "header.original-request": "The original request",
  "header.finished-picture": "Finished picture",
  "header.theme.system": "Theme: follow the OS",
  "header.theme.light": "Theme: light",
  "header.theme.dark": "Theme: dark",
  "header.language": "Language",
  "header.config-unreadable": "Settings file unreadable: switches last only while this page is open",

  "screen.ended": "This brainstorm has ended. Everything stays readable; nothing more can be sent.",
  "screen.back": "Back",
  "screen.unreachable": "The server could not be reached: {reason}",
  "screen.refused": "The server refused the action ({status}).",
  "screen.config-not-saved": "The switch applies to this page only; the settings file could not be written.",

  "card.human": "Human decides",
  "card.why-now": "Why now",
  "card.rests-on": "Rests on",
  "card.in-review": "In review",
  "card.options": "Options",
  "card.recommended": "Recommended",
  "card.consequence": "With this answer",
  "card.prerequisites": "Prerequisites",
  "card.background": "Background",
  "card.note": "Note",
  "card.note-placeholder": "Add a note (optional)",
  "card.defer": "Ask me again next round",
  "card.show-details": "Show details",
  "card.hide-details": "Hide details",
  "card.make-provisional": "Make provisional",
  "card.answer": "Answer",
  "card.deferred-answer": "(deferred)",
  "card.decided-here": "Decided here",
  "card.pre-approved": "Pre-approved",

  "stamp.none": "Approve",
  "stamp.person": "Approved",
  "stamp.pre_approved": "Pre-approved",

  "provisional.title": "Provisional answers",
  "provisional.hint": "Pre-approved by the LLM. Change or send back only what looks wrong.",
  "provisional.open": "Open as a card",
  "provisional.fold": "Fold",
  "provisional.decide-myself": "Decide myself",

  "send.all": "Send all",
  "send.unstamped": "{count} not approved yet",
  "send.ready": "Every question is approved.",
  "send.sent": "Sent. Waiting for the next round.",
  "current.waiting": "Waiting for the first round.",
  "send.proceed": "Proceed with this result",
  "send.review-requests": "Send review requests",
  "send.go-unstamped": "Go to the first question without a stamp",

  "confirm.title": "Send these answers?",
  "confirm.result-title": "Send this?",
  "confirm.result-proceed": "The topic goes on with this result.",
  "confirm.no-questions": "This round has no questions.",
  "confirm.answer": "Answer",
  "confirm.deferred": "Ask me again next round",
  "confirm.note": "Note",
  "confirm.stamp.person": "Approved by you",
  "confirm.review-requests": "Review requests",
  "confirm.send": "Send",
  "confirm.back": "Back",

  "result.title": "Result",
  "result.hint": "The brainstorm has converged. Check the finished picture and the decisions; ask for a review of anything that looks wrong.",
  "result.no-picture": "No finished picture was drawn.",

  "thread.modes": "Show exchanges",
  "thread.latest": "Latest only",
  "thread.all": "All",
  "thread.hidden": "Hide",
  "thread.you": "You",
  "thread.llm": "LLM",
  "thread.writing": "Writing a reply…",
  "thread.no-reply": "No reply",
  "thread.follow-up": "Follow up",
  "thread.following": "Following up on",
  "thread.cancel": "Cancel",
  "thread.ask-placeholder": "Ask about this question",
  "thread.follow-up-placeholder": "Your follow-up",
  "thread.ask": "Ask",
  "thread.quick.more": "Explain more",
  "thread.quick.diagram": "Simplify with a diagram",
  "thread.quick.recommendation": "What does the recommendation mean?",

  "past.none": "No round has been sent yet.",
  "round.number": "Round {number}",

  "records.decisions": "Decisions",
  "records.not-building": "Not building",
  "records.rejected": "Rejected options",
  "records.undecided": "Undecided",
  "records.delegated": "Delegated",
  "records.revisions": "Revised",
  "records.in-review": "In review",
  "records.none": "None yet",
  "records.rejected-in": "Rejected in",
  "records.decider": "Decided by",
  "records.before": "Before",
  "records.after": "After",

  "decision.decided-in": "Decided in",
  "decision.fixed-in": "Fixed in round {round}",
  "decision.revised": "Revised later",
  "decision.review": "Review this",
  "decision.stop-review": "Stop review",

  "fixes.title": "Fixed by the LLM",
  "fixes.new": "(new)",

  "dialog.close": "Close",
  "dialog.decision": "Decision",
  "dialog.no-picture": "No finished picture yet.",

  "map.range": "Range",
  "map.path": "Path",
  "map.all": "All",
  "map.pick-for-path": "Select a point to see what it rests on.",
  "map.selected": "Selected",
  "map.go-to-question": "Go to its question",
  "map.click-to-select": "Click a point to select it.",
  "map.in-review": "In review",
  "map.premise-changed": "Premise changed",
  "map.question": "Question",
  "map.answer-then": "Answer then",
  "map.rejected-because": "Rejected: {reason}",
  "map.column": "Round {round}: {subject}",
  "map.asked-again": "(asked again next round)",
};

const ja = {
  "tab.current": "今のラウンド",
  "tab.past": "過去のラウンド",
  "tab.map": "地図",
  "tab.decisions": "決まったこと",

  "header.untitled": "題名のない議題",
  "header.original-request": "そもそもの議題",
  "header.finished-picture": "完成図",
  "header.theme.system": "テーマ: OS に合わせる",
  "header.theme.light": "テーマ: ライト",
  "header.theme.dark": "テーマ: ダーク",
  "header.language": "言語",
  "header.config-unreadable": "設定ファイルを読めない。切替はこの画面を開いている間だけ効く",

  "screen.ended": "この壁打ちは終わった。どれも読めるが、もう送れない。",
  "screen.back": "戻る",
  "screen.unreachable": "サーバーにつながらない: {reason}",
  "screen.refused": "サーバーが操作を断った（{status}）。",
  "screen.config-not-saved": "設定ファイルに書けなかったので、切替はこの画面だけに効く。",

  "card.human": "人が決める",
  "card.why-now": "なぜ今",
  "card.rests-on": "前提",
  "card.in-review": "見直し中",
  "card.options": "選択肢",
  "card.recommended": "推奨",
  "card.consequence": "この答えだと",
  "card.prerequisites": "前提の決まったこと",
  "card.background": "前提知識",
  "card.note": "補足",
  "card.note-placeholder": "補足（任意）",
  "card.defer": "次のラウンドで聞き直して",
  "card.show-details": "開く",
  "card.hide-details": "たたむ",
  "card.make-provisional": "仮決めにする",
  "card.answer": "答え",
  "card.deferred-answer": "（先送り）",
  "card.decided-here": "ここで決まったこと",
  "card.pre-approved": "代決",

  "stamp.none": "判子を押す",
  "stamp.person": "判子",
  "stamp.pre_approved": "代決",

  "provisional.title": "仮決め",
  "provisional.hint": "LLM が代決している。気になる行だけ選び直すか、差し戻す。",
  "provisional.open": "カードで開く",
  "provisional.fold": "たたむ",
  "provisional.decide-myself": "人が決める問いにする",

  "send.all": "まとめて送る",
  "send.unstamped": "判子のない問いが {count} 問",
  "send.ready": "すべての問いに判子がある。",
  "send.sent": "送った。次のラウンドを待っている。",
  "current.waiting": "最初のラウンドを待っている。",
  "send.proceed": "この結果で進める",
  "send.review-requests": "見直しを頼む",
  "send.go-unstamped": "判子のない最初の問いへ移る",

  "confirm.title": "この答えを送る？",
  "confirm.result-title": "これを送る？",
  "confirm.result-proceed": "この結果で議題を進める。",
  "confirm.no-questions": "このラウンドに問いはない。",
  "confirm.answer": "答え",
  "confirm.deferred": "次のラウンドで聞き直して",
  "confirm.note": "補足",
  "confirm.stamp.person": "本人が押した",
  "confirm.review-requests": "見直したいもの",
  "confirm.send": "送る",
  "confirm.back": "戻る",

  "result.title": "結果",
  "result.hint": "壁打ちが収束した。完成図と決まったことを確かめ、気になるものがあれば見直したいを押す。",
  "result.no-picture": "完成図は描かれていない。",

  "thread.modes": "やり取りの出し方",
  "thread.latest": "最新だけ",
  "thread.all": "全部",
  "thread.hidden": "隠す",
  "thread.you": "本人",
  "thread.llm": "LLM",
  "thread.writing": "書いている…",
  "thread.no-reply": "返事なし",
  "thread.follow-up": "続きとして聞く",
  "thread.following": "続きとして聞く返事",
  "thread.cancel": "やめる",
  "thread.ask-placeholder": "この問いについて聞き返す",
  "thread.follow-up-placeholder": "続きの聞き返し",
  "thread.ask": "聞き返す",
  "thread.quick.more": "詳しく説明して",
  "thread.quick.diagram": "図で噛み砕いて",
  "thread.quick.recommendation": "推奨はどういう意味？",

  "past.none": "まだ送ったラウンドはない。",
  "round.number": "第 {number} ラウンド",

  "records.decisions": "決まったこと",
  "records.not-building": "作らないもの",
  "records.rejected": "見送った案",
  "records.undecided": "未決",
  "records.delegated": "任せたこと",
  "records.revisions": "改めたこと",
  "records.in-review": "見直し中",
  "records.none": "まだない",
  "records.rejected-in": "見送った問い",
  "records.decider": "決める人",
  "records.before": "前",
  "records.after": "後",

  "decision.decided-in": "決まった問い",
  "decision.fixed-in": "第 {round} ラウンドの直したこと",
  "decision.revised": "あとで改めた",
  "decision.review": "見直したい",
  "decision.stop-review": "見直したいをやめる",

  "fixes.title": "直したこと",
  "fixes.new": "（新しく決めた）",

  "dialog.close": "閉じる",
  "dialog.decision": "決まったこと",
  "dialog.no-picture": "完成図はまだない。",

  "map.range": "範囲",
  "map.path": "道筋",
  "map.all": "全部",
  "map.pick-for-path": "点を選ぶと、その点へさかのぼれる分だけを出す。",
  "map.selected": "選んだ点",
  "map.go-to-question": "その問いへ移る",
  "map.click-to-select": "点をクリックすると選べる。",
  "map.in-review": "見直し中",
  "map.premise-changed": "前提が変わった",
  "map.question": "問い",
  "map.answer-then": "そのときの答え",
  "map.rejected-because": "見送った理由: {reason}",
  "map.column": "第 {round} ラウンド: {subject}",
  "map.asked-again": "（次のラウンドで聞き直す）",
};

const TABLES = { en, ja };

/// The text function for `lang`: `t("send.unstamped", { count: 2 })`. An unknown language
/// falls back to English.
export function translator(lang) {
  const table = TABLES[lang] ?? en;
  return (key, vars = {}) => {
    const text = table[key] ?? en[key] ?? key;
    return text.replace(/\{(\w+)\}/g, (_, name) => String(vars[name] ?? ""));
  };
}
