// The screen's fixed text in English and Japanese (docs/spec/screen.md, "言語"). The Japanese
// uses the glossary's words (CONTEXT.md). Text the LLM wrote never passes through here.

const en = {
  "tab.current": "Current round",
  "tab.past": "Past rounds",
  "tab.map": "Map",
  "tab.decisions": "Decisions",

  "header.untitled": "Untitled topic",
  "header.original-request": "The original request",
  "header.finished-picture": "Finished picture",
  "header.theme.system": "Theme: follow the OS",
  "header.theme.light": "Theme: light",
  "header.theme.dark": "Theme: dark",
  "header.language": "Language",
  "header.config-unreadable": "Settings file unreadable: switches last only while this page is open",
  "agent.waiting": "LLM waiting",
  "agent.waiting-title": "The LLM is waiting for what you do on this screen.",
  "agent.working": "LLM working",
  "agent.working-title": "The LLM has received what you sent and is working on it.",
  "agent.not-responding": "LLM not responding",
  "agent.not-responding-title": "The LLM has neither waited nor replied for 10 minutes. Check the session in your terminal.",

  "screen.ended": "This brainstorm has ended. Everything stays readable; nothing more can be sent.",
  "screen.back": "Back",
  "screen.unreachable": "The server could not be reached: {reason}",
  "screen.refused": "The server refused the action ({status}).",
  "screen.config-not-saved": "The switch applies to this page only; the settings file could not be written.",

  "refusal.no_round": "No round has arrived yet.",
  "refusal.round_submitted": "This round has already been sent.",
  "refusal.round_unsent": "Round {round} has not been sent yet.",
  "refusal.topic_ended": "The topic has ended.",
  "refusal.unknown_question": "Question {question} is not in the current round.",
  "refusal.unknown_option": "That option does not exist.",
  "refusal.unknown_ask": "That ask does not exist.",
  "refusal.unknown_decision": "Decision {decision} does not exist.",
  "refusal.already_replied": "That ask already has a reply.",
  "refusal.not_in_review": "Decision {decision} is not in review.",
  "refusal.review_while_round_sent": "Review requests cannot be sent until the next round arrives.",
  "refusal.not_current_round": "Round {round} is no longer the current round; the screen now shows the current one.",
  "refusal.follows_another_question": "That ask is about another question, so this cannot follow it.",
  "refusal.unstamped": "Some questions are not approved yet ({questions}); approve every question before sending.",

  "card.human": "Human decides",
  "card.why-now": "Why now",
  "card.rests-on": "Rests on",
  "card.in-review": "In review",
  "card.options": "Options",
  "card.recommended": "Recommended",
  "card.consequence": "With this answer",
  "card.prerequisites": "Prerequisites",
  "card.background": "Background",
  "card.note": "Note sent with this answer (optional)",
  "card.defer": "Ask me again next round",
  "card.show-details": "Show premises and option details",
  "card.hide-details": "Hide premises and option details",
  "card.make-provisional": "Make provisional",
  "card.answer": "Answer",
  "card.deferred-answer": "(deferred)",
  "card.decided-here": "Decided here",
  "card.pre-approved": "Pre-approved",

  "stamp.none": "Approve",
  "stamp.person": "Approve",
  "stamp.pre_approved": "Pre-approved",

  "provisional.title": "Provisional answers",
  "provisional.hint": "Provisional questions are small ones that are cheap to change later. The LLM has pre-approved each with its recommendation; change or send back only what looks wrong.",
  "provisional.open": "Open as a card",
  "provisional.fold": "Fold back into a row",
  "provisional.decide-myself": "Decide myself",

  "send.all": "Send all",
  "send.unstamped": "{count} not approved yet",
  "send.ready": "Every question is approved.",
  "sent.next-round": "Sent. The LLM is preparing the next round.",
  "sent.proceeded": "You proceeded with this result. The LLM is writing up the specification.",
  "current.waiting": "Waiting for the first round.",
  "send.proceed": "Proceed with this result",
  "send.review-requests": "Send review requests",
  "send.go-unstamped": "Go to the first question without a stamp",

  "confirm.title": "Send these answers?",
  "confirm.result-title": "Send this?",
  "confirm.result-proceed": "The topic goes on with this result.",
  "confirm.no-questions": "This round has no questions.",
  "confirm.answer": "Answer",
  "confirm.deferred": "Ask me again next round",
  "confirm.note": "Note",
  "confirm.stamp.person": "Approved by you",
  "confirm.review-requests": "Review requests",
  "confirm.send": "Send",
  "confirm.back": "Back",

  "result.title": "Result",
  "result.hint": "The brainstorm has converged. Check the finished picture and the decisions; ask for a review of anything that looks wrong.",
  "result.no-picture": "No finished picture was drawn.",

  "thread.heading": "Asks to the LLM ({count})",
  "thread.elided": "… {count} exchanges …",
  "thread.go-to-quoted": "Go to the reply this follows",
  "thread.you": "You",
  "thread.llm": "LLM",
  "thread.writing": "Writing a reply…",
  "thread.no-reply": "No reply",
  "thread.follow-up": "Follow up on this reply",
  "thread.following": "Following up on",
  "thread.cancel": "Cancel",
  "thread.ask-placeholder": "Ask about this question",
  "thread.follow-up-placeholder": "Your follow-up",
  "thread.send": "Send the ask",
  "thread.quick.more": "Explain more",
  "thread.quick.diagram": "Simplify with a diagram",
  "thread.quick.recommendation": "What does the recommendation mean?",

  "past.none": "No round has been sent yet.",
  "past.sent-as.proceeded": "Proceeded with this result",
  "past.sent-as.review_requested": "Asked for a review",
  "round.number": "Round {number}",

  "records.decisions": "Decisions",
  "records.not-building": "Not building",
  "records.rejected": "Rejected options",
  "records.undecided": "Undecided",
  "records.delegated": "Delegated",
  "records.revisions": "Revised",
  "records.in-review": "In review",
  "records.none": "None yet",
  "records.rejected-in": "Rejected in",
  "records.decider": "Decided by",
  "records.before": "Before",
  "records.after": "After",

  "decision.go-to-source": "Go to the question it was decided in",
  "decision.fixed-in": "Fixed in round {round}",
  "decision.revised": "Revised later",
  "decision.review": "Review this",
  "decision.stop-review": "Stop review",

  "review.title": "Review this decision?",
  "review.confirm": "The LLM is told now and asks this again in the next round. You can stop the review until the LLM gives its conclusion.",
  "review.confirm-result": "Send with “Send review requests” and this is asked again in the next round. You can stop the review until the LLM gives its conclusion.",
  "review.yes": "Review",
  "review.no": "Don't review",

  "fixes.title": "Fixed by the LLM",
  "fixes.new": "(new)",

  "dialog.close": "Close",
  "dialog.decision": "Decision",
  "dialog.no-picture": "No finished picture yet.",

  "map.range": "Range",
  "map.path": "Path",
  "map.all": "All",
  "map.pick-for-path": "Select a point and press “Show the path to this” to see what it rests on.",
  "map.go-to-question": "Go to its question",
  "map.show-path": "Show the path to this",
  "map.zoom": "Zoom",
  "map.zoom-in": "Zoom in",
  "map.zoom-out": "Zoom out",
  "map.fit": "Fit",
  "map.how-to-move": "Drag to move, Ctrl/⌘ + wheel or pinch to zoom, click a point for its details.",
  "arrival.round": "Round {n} has arrived",
  "arrival.result": "The result has arrived",
  "arrival.reply": "A reply to “{question}” has arrived",
  "arrival.view": "View",
  "arrival.label": "Arrivals",
  "arrival.empty": "Nothing has arrived yet",
  "map.wheel-ctrl": "Ctrl + wheel to zoom",
  "map.wheel-mac": "⌘ + wheel to zoom",
  "map.in-review": "In review",
  "map.premise-changed": "Premise changed",
  "map.question": "Question",
  "map.answer-then": "Answer then",
  "map.rejected-because": "Rejected: {reason}",
  "map.column": "Round {round}: {subject}",
  "map.asked-again": "(asked again next round)",
};

const ja = {
  "tab.current": "今のラウンド",
  "tab.past": "過去のラウンド",
  "tab.map": "地図",
  "tab.decisions": "決まったこと",

  "header.untitled": "題名のない議題",
  "header.original-request": "そもそもの議題",
  "header.finished-picture": "完成図",
  "header.theme.system": "テーマ: OS に合わせる",
  "header.theme.light": "テーマ: ライト",
  "header.theme.dark": "テーマ: ダーク",
  "header.language": "言語",
  "header.config-unreadable": "設定ファイルを読み込めません。切り替えはこの画面を開いている間だけ有効です",
  "agent.waiting": "LLM 待機中",
  "agent.waiting-title": "LLM はこの画面での操作を待っています。",
  "agent.working": "LLM 作業中",
  "agent.working-title": "LLM は送った内容を受け取り、作業しています。",
  "agent.not-responding": "LLM 応答なし",
  "agent.not-responding-title": "LLM が 10 分間、待機も返事もしていません。ターミナルのセッションを確認してください。",

  "screen.ended": "この壁打ちは終了しました。内容は読めますが、送ることはできません。",
  "screen.back": "戻る",
  "screen.unreachable": "サーバーに接続できません: {reason}",
  "screen.refused": "サーバーが操作を受け付けませんでした（{status}）。",
  "screen.config-not-saved": "設定ファイルに保存できなかったため、切り替えはこの画面にだけ反映されます。",

  "refusal.no_round": "まだラウンドが届いていません。",
  "refusal.round_submitted": "このラウンドは送信済みです。",
  "refusal.round_unsent": "第 {round} ラウンドはまだ送っていません。",
  "refusal.topic_ended": "この議題は終了しています。",
  "refusal.unknown_question": "問い {question} は今のラウンドにありません。",
  "refusal.unknown_option": "その選択肢はありません。",
  "refusal.unknown_ask": "その質問はありません。",
  "refusal.unknown_decision": "決まったこと {decision} はありません。",
  "refusal.already_replied": "その質問には、すでに返事があります。",
  "refusal.not_in_review": "決まったこと {decision} は見直し中ではありません。",
  "refusal.review_while_round_sent": "送ってから次のラウンドが届くまでは、見直すを使えません。",
  "refusal.not_current_round": "第 {round} ラウンドは今のラウンドではなくなりました。今のラウンドを表示しています。",
  "refusal.follows_another_question": "別の問いへの質問なので、続けて質問できません。",
  "refusal.unstamped": "判子のない問いがあります（{questions}）。すべての問いに判子を押してから送ってください。",

  "card.human": "人が決める",
  "card.why-now": "なぜ今",
  "card.rests-on": "前提",
  "card.in-review": "見直し中",
  "card.options": "選択肢",
  "card.recommended": "推奨",
  "card.consequence": "この答えだと",
  "card.prerequisites": "前提の決まったこと",
  "card.background": "前提知識",
  "card.note": "この答えに添えて送る補足（任意）",
  "card.defer": "次のラウンドで聞き直して",
  "card.show-details": "前提と選択肢の説明を見る",
  "card.hide-details": "前提と選択肢の説明を隠す",
  "card.make-provisional": "仮決めにする",
  "card.answer": "答え",
  "card.deferred-answer": "（先送り）",
  "card.decided-here": "ここで決まったこと",
  "card.pre-approved": "代決",

  "stamp.none": "判子を押す",
  "stamp.person": "確認",
  "stamp.pre_approved": "代決",

  "provisional.title": "仮決め",
  "provisional.hint": "仮決めは、あとで変えても困らない小さな問いです。LLM が推奨で先に判子を押しています（代決）。気になる行だけ選び直すか、差し戻してください。",
  "provisional.open": "カードで見る",
  "provisional.fold": "行に戻す",
  "provisional.decide-myself": "人が決める問いにする",

  "send.all": "まとめて送る",
  "send.unstamped": "判子のない問い: {count} 問",
  "send.ready": "すべての問いに判子があります。",
  "sent.next-round": "送信しました。LLM が次のラウンドを用意しています。",
  "sent.proceeded": "この結果で進めました。LLM が仕様をまとめています。",
  "current.waiting": "最初のラウンドを待っています。",
  "send.proceed": "この結果で進める",
  "send.review-requests": "見直しを頼む",
  "send.go-unstamped": "判子のない最初の問いへ移動",

  "confirm.title": "この内容で送りますか？",
  "confirm.result-title": "この内容で送りますか？",
  "confirm.result-proceed": "この結果で議題を進めます。",
  "confirm.no-questions": "このラウンドに問いはありません。",
  "confirm.answer": "答え",
  "confirm.deferred": "次のラウンドで聞き直して",
  "confirm.note": "補足",
  "confirm.stamp.person": "本人が押した判子",
  "confirm.review-requests": "見直し中のもの",
  "confirm.send": "送る",
  "confirm.back": "戻る",

  "result.title": "結果",
  "result.hint": "壁打ちがまとまりました。完成図と決まったことを確かめて、気になるものがあれば「見直す」を押してください。",
  "result.no-picture": "完成図はありません。",

  "thread.heading": "LLM への質問（{count}）",
  "thread.elided": "… {count} 件のやり取りを省略 …",
  "thread.go-to-quoted": "引用元の返事へ移動",
  "thread.you": "本人",
  "thread.llm": "LLM",
  "thread.writing": "返事を書いています…",
  "thread.no-reply": "返事なし",
  "thread.follow-up": "この返事に続けて質問",
  "thread.following": "続けて質問する返事",
  "thread.cancel": "キャンセル",
  "thread.ask-placeholder": "この問いについて質問する",
  "thread.follow-up-placeholder": "続きの質問",
  "thread.send": "送信",
  "thread.quick.more": "詳しく説明して",
  "thread.quick.diagram": "図でかみ砕いて説明して",
  "thread.quick.recommendation": "推奨はどういう意味ですか？",

  "past.none": "送ったラウンドはまだありません。",
  "past.sent-as.proceeded": "この結果で進めました",
  "past.sent-as.review_requested": "見直しを頼みました",
  "round.number": "第 {number} ラウンド",

  "records.decisions": "決まったこと",
  "records.not-building": "作らないもの",
  "records.rejected": "見送った案",
  "records.undecided": "未決",
  "records.delegated": "任せたこと",
  "records.revisions": "改めたこと",
  "records.in-review": "見直し中",
  "records.none": "まだありません",
  "records.rejected-in": "見送った問い",
  "records.decider": "決める人",
  "records.before": "前",
  "records.after": "後",

  "decision.go-to-source": "元の問いへ移動",
  "decision.fixed-in": "第 {round} ラウンドで直したこと",
  "decision.revised": "後から改めた",
  "decision.review": "見直す",
  "decision.stop-review": "見直しをやめる",

  "review.title": "この決まったことを見直しますか？",
  "review.confirm": "LLM に伝えて、次のラウンドで問い直してもらいます。LLM が見直しの結論を出すまでは、見直しをやめられます。",
  "review.confirm-result": "見直しを頼むで送ると、次のラウンドで問い直されます。LLM が見直しの結論を出すまでは、見直しをやめられます。",
  "review.yes": "見直す",
  "review.no": "見直さない",

  "fixes.title": "直したこと",
  "fixes.new": "（新規）",

  "dialog.close": "閉じる",
  "dialog.decision": "決まったこと",
  "dialog.no-picture": "完成図はまだありません。",

  "map.range": "範囲",
  "map.path": "道筋",
  "map.all": "全部",
  "map.pick-for-path": "点を選んで「ここまでの道筋を表示」を押すと、その点に至る道筋だけを表示します。",
  "map.go-to-question": "この問いへ移動",
  "map.show-path": "ここまでの道筋を表示",
  "map.zoom": "拡大と縮小",
  "map.zoom-in": "拡大",
  "map.zoom-out": "縮小",
  "map.fit": "全体",
  "map.how-to-move": "ドラッグで移動、Ctrl/⌘＋ホイールかピンチで拡大・縮小。点をクリックすると詳細を表示します。",
  "arrival.round": "第 {n} ラウンドが届きました",
  "arrival.result": "結果が届きました",
  "arrival.reply": "{question}への返事が届きました",
  "arrival.view": "見る",
  "arrival.label": "届いたもの",
  "arrival.empty": "まだ届いたものはありません",
  "map.wheel-ctrl": "Ctrl＋ホイールで拡大",
  "map.wheel-mac": "⌘＋ホイールで拡大",
  "map.in-review": "見直し中",
  "map.premise-changed": "前提が変わった",
  "map.question": "問い",
  "map.answer-then": "当時の答え",
  "map.rejected-because": "見送った理由: {reason}",
  "map.column": "第 {round} ラウンド: {subject}",
  "map.asked-again": "（次のラウンドで聞き直し）",
};

const TABLES = { en, ja };

/// Whether the table has a text for `key`; the text function falls back to the key itself.
export const knows = (key) => key in en;

/// The text function for `lang`: `t("send.unstamped", { count: 2 })`. An unknown language
/// falls back to English.
export function translator(lang) {
  const table = TABLES[lang] ?? en;
  return (key, vars = {}) => {
    const text = table[key] ?? en[key] ?? key;
    return text.replace(/\{(\w+)\}/g, (_, name) => String(vars[name] ?? ""));
  };
}
